github:
  client:
    id: 6ba7563aba27ac13209a
    secret: 393963ee9a334a500f7e6971e95c2ce7234ab107
  redirect:
    uri: http://localhost:8080/callback

## 配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

## 整合mybatis
mybatis:
  type-aliases-package: com.mine.project.project1.model
  mapper-locations: classpath:mybatis/mapper/*.xml
